apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: voting-app
data:
  app.name: "Voting App"
  app.environment: "production"
  
  redis.host: "redis-master.voting-app.svc.cluster.local"
  redis.port: "6379"
  
  postgres.host: "postgresql.voting-app.svc.cluster.local"
  postgres.port: "5432"
  postgres.database: "voting"