apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: voting-app
type: Opaque
stringData:
  postgres-username: "votinguser"
  postgres-password: "votingpass123"
  redis-password: "redispass123"