apiVersion: v1
kind: Namespace
metadata:
  name: voting-app
  labels:
    name: voting-app
    environment: production
    app.kubernetes.io/name: voting-app
    app.kubernetes.io/part-of: voting-system